---
#config MariaDB on DB
    - hosts: db
      vars_files:
        - inventories/production/group_vars/all/all.yml
        - inventories/production/group_vars/all/vault.yml
      roles:
            - config_db