---
        - name: Django setup
          package: 
            name: python-django
            state: present
        
        - name: Gunicorn setup
          package: 
            name: gunicorn
            state: present
            
        - name: ubuntu gunicorn run
          gunicorn:
            app: "my.wsgi:application"
            chdir: "/pan/my"
            conf: "/pan/my/gunicorn.conf"