---
 #       - name: python-dev setup
 #         package: 
  #          name: python-dev
 #           state: present
        
        - name: Django setup
          package: 
            name: python-django
            state: present
                                
        - name: python-pymysql MySQL-python setup
          package: 
            name: python-mysqldb 
            state: present
        
        - name: python-pymysql setup
          package: 
            name: python-pymysql
            state: present
        
        - name: Gunicorn setup
          package: 
            name: gunicorn
            state: present
            
        - name: ubuntu gunicorn run
          gunicorn:
            app: "my.wsgi:application"
            chdir: "/pan/my"
            conf: "/pan/my/gunicorn.conf"