---
#roles/django_host_co/tasks/main.yml
        - name: Django setup
          package: 
            name: python-django
            state: present
            
        - name: MySQL-python setup
          package: 
            name: MySQL-python 
            state: present
        
        - name: Gunicorn setup
          package: 
            name: python-gunicorn
            state: present
            
        - name: centos gunicorn run
          gunicorn:
            app: "my.wsgi:application"
            chdir: "/pan/my"
            conf: "/pan/my/gunicorn.conf"