---
        - name: python-dev setup
          package: 
            name: python-dev 
            state: present
            
        - name: libmysqlclient-dev setup
          package: 
            name: libmysqlclient-dev 
            state: present
                
        - name: Install pip
          package:
            name: python-pip
            state: present
            
        - name: Installs MySQL-python
          pip: 
            name: MySQL-python    
            
        - name: Installs flask-mysql
          pip: 
            name: flask-mysql

        - name: Installs gunicorn
          pip: 
            name: gunicorn
            
        - name: Deploy the flask app
          template:
            src: mypan.py.j2
            dest: /pan/mypan.py
            
        - name: centos gunicorn run
          gunicorn:
            app: "mypan:app"
            chdir: "/pan"
            conf: "/pan/gunicorn.conf"
     
            
            
